<!-- Profile -->
<div class="w3-card-2 w3-round w3-white">
    <div class="w3-container">
        <h4 class="w3-center"><?= $fullname ?></h4>
        <p class="w3-center"><img src="/app/templates/w3images/avatar3.png" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
        <hr>
        <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i><?= $email ?></p>
        <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> <?= $birthday ?></p>
    </div>
</div>