<!DOCTYPE html>
<html>
<title><?= $loggedUser->firstName.' '. $loggedUser->lastName ?></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/app/templates/lib/w3.css">
<link rel="stylesheet" href="/app/templates/lib/w3-theme-blue-grey.css">
<link rel="stylesheet" href="/app/templates/lib/dialog.css">
<link rel="stylesheet" href="/app/templates/lib/bootstrap-chosen.css">

<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="/app/templates/lib/chosen.js"></script>

<style>
    html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}
</style>

<body class="w3-theme-l5">

<!-- Navbar -->
<div class="w3-top">
    <ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
        <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
            <a class="w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
        </li>
        <li><a href="/" class="w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>ThinkSocial</a></li>
        <li class="w3-hide-small"><a href="/dialogs" class="w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-envelope"></i>
                <?php if ($unreadCounter != 0) : ?>
                    <span class="w3-badge w3-right w3-small w3-green"><?= $unreadCounter?></span>
                <?php else : ?>
                    <span class="w3-badge w3-right w3-small w3-green"></span>
                <?php endif; ?>
            </a></li>
        <li class="w3-hide-small w3-right"><a href="/logout" class="w3-padding-large w3-hover-white" title="Log Out"><img src="/app/templates/w3images/avatar2.png" class="w3-circle" style="height:25px;width:25px" alt="Avatar"></a></li>
    </ul>
</div>
